baseURL = "https://abetar0.net/"

languageCode = "ja-jp"
title = "abetar0.net"
theme = "archie"
copyright = "© abetar0"

[params]
    favicon = "/icons/cat.png"

#[[menu.main]]
#name = "記事"
#url = "/posts"
#weight = 0

[[menu.main]]
name = "About"
url = "/about"
weight = 1

